AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "lib/classnt.rb"

Metrics/PerceivedComplexity:
  Max: 10

Lint/StructNewOverride:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - "lib/classnt.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/classnt.rb"
